baseURL: https://digitalevidencetoolkit.org
languageCode: en-gb
title: The Digital Evidence Preservation Toolkit
author: Basile Simon
copyright: "Copyright © 2021-25, Basile Simon"
theme: hugo-bearblog
enableRobotsTXT: true

disableKinds:
  - taxonomy

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  openGraph: true
  description: An archiving and annotation tool demonstrating chain of custody in view of international prosecutions
  hideMadeWithLine: true

permalinks:
  news: "/news/:slug"
