baseURL: https://digitalevidencetoolkit.org
languageCode: en-gb
title: The Digital Evidence Preservation Toolkit
author: Basile Simon
copyright: "Copyright © 2021-25, Basile Simon"
theme: hugo-bearblog
enableRobotsTXT: true

disableKinds:
  - taxonomy

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  openGraph: true
  description: Preserve, authenticate and present digital evidence with advanced chain-of-custody tracking. Ensure data integrity and courtroom-ready results for legal professionals, archivists, and investigators.
  hideMadeWithLine: true
  meta:
    favicon: true
  author: Basile Simon

  # Social media handles for Open Graph and schema.org
  twitter: "basilesimon"
  mastodon: "https://vis.social/@basilesimon"
  github: "https://github.com/digitalevidencetoolkit"

  # Default image for social sharing (1200x630 optimal)
  defaultImage: "/images/og-default.png"
  images: ["/images/og-default.png"]

  # Licensing and attribution for AI crawlers
  license: "https://creativecommons.org/licenses/by/4.0/"
  licenseName: "CC BY 4.0"
  copyrightHolder: "Basile Simon"
  copyrightYear: "2021-2025"

  # Organization details for schema.org
  organizationName: "Digital Evidence Toolkit"
  organizationType: "Project"

permalinks:
  news: "/news/:slug"

outputs:
  home:
    - html
  news:
    - html
    - feed
outputFormats:
  feed:
    baseName: index
    mediaType: application/rss+xml
    isPlainText: false
    isHTML: false
