name: Build static with Boot

on:
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v1
        with:
          java-version: '15.0.2'
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
          
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.8.0'
          boot: '2.7.2'

      - run: boot -V
